### ISSUE TITLE
[Bug]: Cannot find module '@webassemblyjs/helper-module-context' after Next.js 12 upgrade

### ISSUE THREAD

**Issue by james-work-account** [netlify/netlify-plugin-nextjs#755]
### Steps to reproduce

After upgrading a repo from Next.js 11.1.2 to 12.0.1, deploy preview is failing at the "Functions bundling" stage with the error:

```
8:24:34 PM:   Error message
8:24:34 PM:   A Netlify Function failed to require one of its dependencies.
8:24:34 PM:   Please make sure it is present in the site's top-level "package.json".
​
8:24:34 PM:   In file "/opt/build/repo/.netlify/functions-internal/next_sitemapxml/next_sitemapxml.js"
8:24:34 PM:   Cannot find module '@webassemblyjs/helper-module-context'
```

(see below for link to deploy details and relevant logs)

This error wasn't present when deploying my site after a change earlier today.

**Note: repo is private. If needed, I can add you as a collaborator.**

next.config.js:
```
const withPWA = require("next-pwa");
const runtimeCaching = require("next-pwa/cache");

module.exports = withPWA({
  pwa: {
    dest: "public",
    runtimeCaching,
    disable: process.env.NODE_ENV === "development",
    buildExcludes: [/middleware-manifest.json$/],
  },
});
```

package.json:
```
{
  "name": "lagunasdream",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^12.0.1",
    "next-pwa": "^5.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sass": "^1.35.2"
  },
  "devDependencies": {
    "@types/react": "^17.0.14",
    "typescript": "^4.3.5"
  }
}
```

### A link to a reproduction repository

https://github.com/james-work-account/lagunasdream

### More information about your build

- [X] I am building using the CLI
- [ ] I am building using file-based configuration (netlify.toml)

### What OS are you using?

Mac OS

### Relevant log output (or link to your logs)

https://app.netlify.com/sites/lagunasdream/deploys/617c4a1e7910540008855f2f

```
8:21:13 PM: ────────────────────────────────────────────────────────────────
8:21:13 PM:   5. Functions bundling                                         
8:21:13 PM: ────────────────────────────────────────────────────────────────
8:21:13 PM: ​
8:21:13 PM: Packaging Functions from .netlify/functions-internal directory:
8:21:13 PM:  - next_image/next_image.js
8:21:13 PM:  - next_sitemapxml/next_sitemapxml.js
8:21:13 PM: ​
8:21:16 PM: ​
8:21:16 PM: ────────────────────────────────────────────────────────────────
8:21:16 PM:   Dependencies installation error                               
8:21:16 PM: ────────────────────────────────────────────────────────────────
8:21:16 PM: ​
8:21:16 PM:   Error message
8:21:16 PM:   A Netlify Function failed to require one of its dependencies.
8:21:16 PM:   Please make sure it is present in the site's top-level "package.json".
​
8:21:16 PM:   In file "/opt/build/repo/.netlify/functions-internal/next_sitemapxml/next_sitemapxml.js"
8:21:16 PM:   Cannot find module '@webassemblyjs/helper-module-context'
8:21:16 PM:   Require stack:
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/zisi/resolve.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/zisi/traverse.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/esbuild/src_files.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/esbuild/index.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/bundlers/index.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/node/index.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/index.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/zip-it-and-ship-it/dist/main.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins_core/functions/index.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/steps/get.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/core/main.js
8:21:16 PM:   - /opt/buildhome/node-deps/node_modules/@netlify/build/src/core/bin.js
8:21:16 PM: ​
8:21:16 PM:   Resolved config
8:21:16 PM:   build:
8:21:16 PM:     command: next build
8:21:16 PM:     commandOrigin: ui
8:21:16 PM:     environment:
8:21:16 PM:       - REVIEW_ID
8:21:16 PM:     publish: /opt/build/repo
8:21:16 PM:     publishOrigin: ui
8:21:16 PM:   functions:
8:21:16 PM:     '*':
8:21:16 PM:       included_files:
8:21:16 PM:         - '!node_modules/@next/swc-*/**/*'
8:21:16 PM:         - '!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*'
8:21:16 PM:   headers:
8:21:22 PM:     - for: /_next/static/chunks/*
      values:
        cache-control: public, max-age=31536000, immutable
  plugins:
    - inputs: {}
      origin: ui
      package: '@netlify/plugin-nextjs'
    - inputs: {}
      origin: ui
      package: netlify-plugin-cache-nextjs
  redirects:
    - from: /_next/data/te8vWCF7IDFQxyISkyZrR/sitemap.xml.json
      status: 200
      to: /.netlify/functions/next_sitemapxml
    - from: /sitemap.xml
      status: 200
      to: /.netlify/functions/next_sitemapxml
    - force: true
      from: /_next/image*
      query:
        q: ':quality'
        url: ':url'
        w: ':width'
      status: 301
      to: /nextimg/:url/:width/:quality
    - from: /nextimg/*
      status: 200
      to: /.netlify/functions/next_image
Caching artifacts
8:21:22 PM: Started saving node modules
8:21:22 PM: Finished saving node modules
8:21:22 PM: Started saving build plugins
8:21:22 PM: Finished saving build plugins
8:21:22 PM: Started saving pip cache
8:21:22 PM: Finished saving pip cache
8:21:22 PM: Started saving emacs cask dependencies
8:21:22 PM: Finished saving emacs cask dependencies
8:21:22 PM: Started saving maven dependencies
8:21:22 PM: Finished saving maven dependencies
8:21:22 PM: Started saving boot dependencies
8:21:22 PM: Finished saving boot dependencies
8:21:22 PM: Started saving rust rustup cache
8:21:22 PM: Finished saving rust rustup cache
8:21:22 PM: Started saving go dependencies
8:21:22 PM: Finished saving go dependencies
8:21:22 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
8:21:22 PM: Creating deploy upload records
8:21:22 PM: Failing build: Failed to build site
8:21:22 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
8:21:22 PM: Finished processing build request in 1m47.953634256s
```

**Comment by james-work-account** [comment]
After reverting to Next 11, this error goes away.

**Comment by ascorbic** [comment]
Hi. Can you try the beta version 4 of the build plugin? There are instructions in the readme for how to upgrade

**Comment by jonioni** [comment]
Hi @ascorbic, we tried beta version 4 of the build plugin (for Next 12) following the readme as suggested. 

```toml
[build]
  command = "yarn build"
  publish = ".next"
[[plugins]]
  package = "@netlify/plugin-nextjs"
```

But it seems only three internal functions were deployed:
- ` ___netlify-handler`
- `___netlify-odb-handler`
- `_ipx`

Which results in page not found error: 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/31494475/140334871-30b517cb-5fda-4982-b321-b530cd8aa806.png">

Currently there is no `distDir` setting and everything follows the beta version readme.

**Comment by james-work-account** [comment]
Raised a new PR on my repo with Next 12 and the beta v4 plugin and that seems to have worked. Thanks!
